### ISSUE TITLE
cancel button not visible

### ISSUE THREAD

**Issue by kangsojeong** [flutter-package/images_picker#13]
if I enter albums,
I can't see the cancel button.

**Comment by kangsojeong** [comment]
ios 14.4

**Comment by Thaontt306** [comment]
I get the same issue because language setting in my device is VNese, so I think this package will support well for English, Japanese, Chinese. You can switch to these languages to check it.

**Comment by chavesgu** [comment]
@kangsojeong   @Thaontt306 
I‘m sorry for your problem,At present, the plugin support languages is less.
I will improve this in future days

**Comment by chavesgu** [comment]
I will update [ZLPhotoBrowser](https://github.com/longitachi/ZLPhotoBrowser#Languages) version for more Languages

**Comment by chavesgu** [comment]
@kangsojeong @Thaontt306
please use `images_picker: ^0.0.9`

**Comment by JIS-EON** [comment]
@Thaontt306 @chavesgu thank you very much~!!!!!
