### ISSUE TITLE
i want to change language

### ISSUE THREAD

**Issue by kangsojeong** [flutter-package/images_picker#17]
i want to change some language

example, android 최대 20 달러 자 그림 선택

**Comment by chavesgu** [comment]
plugin language is follow your phone language

**Comment by JIS-EON** [comment]
same here.
I use Korean but translated words in app are little weird. (even 'GIF' changes to Korean)
So I want to change the language of all the parts that used this library to Eng, without change my phone language.
I already tried some ways to change language like intl, but it didn't worked.
Do you have any ideas or settings of this issue? thx.

**Comment by chavesgu** [comment]
@kangsojeong    Do you have the same needs as  @JIS-EON ?     
I can provide a new attr to set plugin's language.
And the behaviour of 'GIF' changes to Korean   because of [PictureSelector](https://github.com/LuckSiege/PictureSelector)
Wait for 1.1.0 or fork my code

**Comment by JIS-EON** [comment]
I'll looking forward to update.
Thanks a lot for your fast feedback ;D

**Comment by chavesgu** [comment]
> I'll looking forward to update.
> Thanks a lot for your fast feedback ;D

I will update to 1.1.0 today, now I am testing language feature

**Comment by JIS-EON** [comment]
> I will update to 1.1.0 today, now I am testing language feature

thx again. I'll use new version immediately after update.

**Comment by chavesgu** [comment]
because some reason, this feature will take many days

**Comment by chavesgu** [comment]
wait a pr merge, I will update to 1.1.0
[https://github.com/LuckSiege/PictureSelector/pull/1908](https://github.com/LuckSiege/PictureSelector/pull/1908)

**Comment by JIS-EON** [comment]
> wait a pr merge, I will update to 1.1.0
> [LuckSiege/PictureSelector#1908](https://github.com/LuckSiege/PictureSelector/pull/1908)

checked. Thx so much XD

**Comment by chavesgu** [comment]
@JIS-EON   @kangsojeong   hey, you can use [v1.1.0](https://pub.dev/packages/images_picker)
