### ISSUE TITLE
Android resource linking failed  

### ISSUE THREAD

**Issue by zicheng-j** [flutter-package/images_picker#18]
Flutter build apk 时报错， images_picker 0.0.9 
* What went wrong:                                                      
Execution failed for task ':app:processReleaseResources'.               
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/jz/.gradle/caches/transforms-2/files-2.1/1dc4659e6e9637d955b4d8e892d8a8e9/picture_library-v2.6.0/AndroidManifest.xml:14:5-21:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by chavesgu** [comment]
你的compileSdkVersion和targetSdkVersion 低了   设为30

**Comment by zicheng-j** [comment]
images_picker 退回到0.0.6 就没问题了

**Comment by zicheng-j** [comment]
> 你的compileSdkVersion和targetSdkVersion 低了 设为30

compileSdkVersion 30
minSdkVersion 21
targetSdkVersion 30 
这样设置还是不行 报同样的错误

**Comment by chavesgu** [comment]
啊 、。说错了。不是sdk原因。是你打包安装的gradle版本低了、
`android/build.gradle`中设置classpath `classpath 'com.android.tools.build:gradle:4.0.1'` 将gradle升级
