### ISSUE TITLE
"I know the"

### ISSUE THREAD

**Issue by erkihindo** [flutter-package/images_picker#20]
If user can only choose 1 image.

1 image is chosen and user clicks on another image, then in a better design, it would just deselect the first one. But here, it gives this weird message.

<img width="359" alt="Screenshot at Apr 20 17-11-12" src="https://user-images.githubusercontent.com/16940944/115410751-8e3a9800-a1fb-11eb-8b16-b46a2f081be6.png">

**Comment by chavesgu** [comment]
I don't think so.

**Comment by Srj-Love** [comment]
Hey., this issue is exist please check again.
