### ISSUE TITLE
Android 拍照白屏幕

### ISSUE THREAD

**Issue by gaoguanqi** [flutter-package/images_picker#21]
作者你好，在使用这个库时遇到了问题，拍照点击对号后白屏了， 红米 7.0,  
![image](https://user-images.githubusercontent.com/12546980/115489698-35b4da80-a28f-11eb-891f-d76cbe014aa2.png)
![image](https://user-images.githubusercontent.com/12546980/115489725-45342380-a28f-11eb-9a73-10c740ca5f8a.png)

**Comment by chavesgu** [comment]
这个不是我控制的，你需要去[PictureSelector](https://github.com/LuckSiege/PictureSelector)提issue

**Comment by chavesgu** [comment]
另外你这里的provider是什么意思   我写的这个插件用不到这个

**Comment by gaoguanqi** [comment]
好的， 我运行 这个库的 example 就没问题，不知道为什么

**Comment by yingzhong27** [comment]
你好 请问你解决了嘛？ 我这边也是 拍照以后直接回到了我的闪屏页 没有任何错误
