### ISSUE TITLE
ImagesPicker.pick returns null

### ISSUE THREAD

**Issue by MustafaAdam** [flutter-package/images_picker#22]
The example code returns a null.

      List<Media> res = await ImagesPicker.pick(
        count: 1,
        pickType: PickType.image,
      );

res variable is a null variable. How to fix this?

**Comment by chavesgu** [comment]
you need provide logcat or xcode log

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Mustafa Adam ***@***.***&gt;;
发送时间：2021年4月28日(星期三) 凌晨4:10
收件人："flutter-package/images_picker" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[flutter-package/images_picker] ImagesPicker.pick returns null (#22)
-----------------------------------

 

 
The example code returns a null.
   List<Media&gt; res = await ImagesPicker.pick(     count: 1,     pickType: PickType.image,   );  
res variable is a null variable. How to fix this?

**Comment by chavesgu** [comment]
Normal, when user cancel pick, plugin will return null.

**Comment by AgarwalsRahul** [comment]
final image = await ImagesPicker.openCamera(
        language: Language.English,
        quality: 1.0,
        pickType: PickType.image,
      );

It closes the app as soon as this function runs.
