### ISSUE TITLE
Video creation is taking very long time 

### ISSUE THREAD

**Issue by ravitejaavv** [flutter-package/images_picker#23]
Currently the recorded video will be processed and stored in this path "data/....../cache/.."
Until then user has to wait to get the path of the video. 

Is there a way to get the path of the recorded video immediately ?? (I don't want any video processing and it has to be stored in default location of Camera videos)

**Comment by chavesgu** [comment]
I know your mean、I will check for this、

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："RaviTeja Aketi ***@***.***&gt;;
发送时间：2021年4月28日(星期三) 中午1:42
收件人："flutter-package/images_picker" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[flutter-package/images_picker] Video creation is taking very long time  (#23)
-----------------------------------

 

 
Currently the recorded video will be processed and stored in this path "data/....../cache/.."
 Until then user has to wait to get the path of the video.
 
Is there a way to get the path of the recorded video immediately ?? (I don't want any video processing and it has to be stored in default location of Camera videos)

**Comment by chavesgu** [comment]
I detele some superfluous action in android. Please use `v1.2.2`

**Comment by ravitejaavv** [comment]
> v1.2.2

sure i will check and get back to you

**Comment by ravitejaavv** [comment]
Hi @chavesgu 

Facing another issue.

1) Open the camera and Record the video & finish. Here i am able to receive the path immediately.
2) Again call open camera to recapture the video again
3) Now i am unable to start the record due to following error

"Cannot start video capture. Another app may be using the mic "

![Screenshot_20210428-152304_20210428_152458470](https://user-images.githubusercontent.com/33521315/116385263-4092e080-a836-11eb-8e2c-f7d27c282fa8.jpg)

**Comment by ravitejaavv** [comment]
> Hi @chavesgu
> 
> Facing another issue.
> 
> 1. Open the camera and Record the video & finish. Here i am able to receive the path immediately.
> 2. Again call open camera to recapture the video again
> 3. Now i am unable to start the record due to following error
> 
> "Cannot start video capture. Another app may be using the mic "
> 
> ![Screenshot_20210428-152304_20210428_152458470](https://user-images.githubusercontent.com/33521315/116385263-4092e080-a836-11eb-8e2c-f7d27c282fa8.jpg)

I feel this might be due to Video Player. I am playing the preview in the video player. This might be causing the problem. I will close this.

**Comment by ravitejaavv** [comment]
Hi @chavesgu

Facing another issue.

* Open the camera and Record the video & finish. Here i am able to receive the path immediately.
* Preview in video player
* Again call open camera to recapture the video again
* Now i am unable to start the record due to following error
"Cannot start video capture. Another app may be using the mic "

![Screenshot_20210428-152304_20210428_152458470](https://user-images.githubusercontent.com/33521315/116397892-c4ec6000-a844-11eb-86b0-0ad17d8b67d3.jpg)

Do you think this issue is due to Video Player ?

**Comment by chavesgu** [comment]
You can pause video player when you want to record. I think it is not bug in my plugin
