### ISSUE TITLE
Access image name and type

### ISSUE THREAD

**Issue by Urkman** [flutter-package/images_picker#25]
How can I access the image name and the type(jpeg, png or heif)?

**Comment by chavesgu** [comment]
it‘s not support

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Stefan Sturm ***@***.***&gt;;
发送时间：2021年5月3日(星期一) 凌晨4:22
收件人："flutter-package/images_picker" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[flutter-package/images_picker] Access image name and type (#25)
-----------------------------------

 

 
How can I access the image name and the type(jpeg, png or heif)?

**Comment by Urkman** [comment]
Is it possible to add it? It would make things way easier, as we need to know the file type on backend side :)

**Comment by chavesgu** [comment]
1. if you set compress param, it must return JPG type , because only JPG support compress
2. if you did not set compress, it will return type itself in gallery.
3. if you want get file type,you should get the suffix of string you get

**Comment by chavesgu** [comment]
please use version `1.2.4`.
I did some stupid things in `1.2.3`
