### ISSUE TITLE
App crashes on Android when calling .openCamera method

### ISSUE THREAD

**Issue by saarikivit** [flutter-package/images_picker#26]
Hi! :wave: Thanks for the amazing tool :smile: 

What happens:
The app crashes when I call the method below.

Device:
Android 10, Oneplus 5t, real device plugged in on a Ubuntu LTS machine.

Platform:
Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (4 days ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3

The method:
```dart
  Future<List<Media>?> openCamera() async {
    final List<Media>? result = await ImagesPicker.openCamera(
      maxSize: 1000,
      pickType: PickType.image,
      quality: 0.9,
    );

    if (result == null) {
      return null;
    }

    if (result.isEmpty) {
      return null;
    }

    final File file = File(result.first.path);
    await ImagesPicker.saveImageToAlbum(file, albumName: 'my album name');

    return result;
  }
```

Error logs:
`
D/ViewRootImpl[MainActivity](29832): windowFocusChanged hasFocus=false inTouchMode=true
W/MapperHal(29832): buffer descriptor with invalid usage bits 0x2000
D/PhoneWindow(29832): setNavigationBarColor: 0
W/m.carrotkitche(29832): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/m.carrotkitche(29832): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/AndroidRuntime(29832): Shutting down VM
E/AndroidRuntime(29832): FATAL EXCEPTION: main
E/AndroidRuntime(29832): Process: com.carrotkitchen, PID: 29832
E/AndroidRuntime(29832): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.carrotkitchen/com.luck.picture.lib.PictureSelectorCameraEmptyActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
E/AndroidRuntime(29832): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3375)
E/AndroidRuntime(29832): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3514)
E/AndroidRuntime(29832): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(29832): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(29832): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(29832): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
E/AndroidRuntime(29832): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(29832): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(29832): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
E/AndroidRuntime(29832): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29832): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(29832): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(29832): Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
E/AndroidRuntime(29832): 	at java.lang.String.substring(String.java:2064)
E/AndroidRuntime(29832): 	at com.luck.picture.lib.tools.StringUtils.renameSuffix(StringUtils.java:83)
E/AndroidRuntime(29832): 	at com.luck.picture.lib.PictureBaseActivity.startOpenCamera(PictureBaseActivity.java:647)
E/AndroidRuntime(29832): 	at com.luck.picture.lib.PictureSelectorCameraEmptyActivity.startCamera(PictureSelectorCameraEmptyActivity.java:120)
E/AndroidRuntime(29832): 	at com.luck.picture.lib.PictureSelectorCameraEmptyActivity.onTakePhoto(PictureSelectorCameraEmptyActivity.java:101)
E/AndroidRuntime(29832): 	at com.luck.picture.lib.PictureSelectorCameraEmptyActivity.onCreate(PictureSelectorCameraEmptyActivity.java:71)
E/AndroidRuntime(29832): 	at android.app.Activity.performCreate(Activity.java:7815)
E/AndroidRuntime(29832): 	at android.app.Activity.performCreate(Activity.java:7804)
E/AndroidRuntime(29832): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1325)
E/AndroidRuntime(29832): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3350)
E/AndroidRuntime(29832): 	... 11 more
I/Process (29832): Sending signal. PID: 29832 SIG: 9
Lost connection to device.
Exited (sigterm)
`

PS. the camera worked fine on 1.2.0. :1st_place_medal:

**Comment by chavesgu** [comment]
please use version `1.2.4`.
I did some stupid things in `1.2.3`
