### ISSUE TITLE
Add maxTime to pick method

### ISSUE THREAD

**Issue by mhnowak** [flutter-package/images_picker#29]
## Environment

**Flutter version:** Any
**Plugin version:**    Next
**Android version:**    Any
**iOS version:** Any
**Xcode version:** Any
**Device information:**   Any

## Description

**What you'd like to happen:** Be able to limit displayed videos to only those that fulfil time requirements.

**Alternatives you've considered:** Using `image_picker` plugin instead, but it doesn't allow for selecting videos/images simultaneously

**Comment by chavesgu** [comment]
did you want a param to filter videos time in album？

**Comment by mhnowak** [comment]
@chavesgu yes

**Comment by chavesgu** [comment]
please use newest version
