### ISSUE TITLE
is it possible to show images_picker in bottom sheet?

### ISSUE THREAD

**Issue by rmControls** [flutter-package/images_picker#36]
first of all congratulations for developing this great package...

I felt like it is far better and more advanced package then google `image_picker`..

I am looking little customization to match my app theme and style...

I have two questions?
1) is it possible to show images in bottom sheet like in [this](https://github.com/kroegerama/bottomsheet-imagepicker) or [this](https://github.com/ParkSangGwon/TedBottomPicker)
2) is it possible to change appbar color, ticker color and font style... etc.,

**Comment by chavesgu** [comment]
thanks for using.
But about your question，I am sorry to say no
1、bottom picker is not common feature
2、plugin style is wechat app picker style，if you want other style ui，you need fork

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："rmControls ***@***.***&gt;;
发送时间：2021年6月30日(星期三) 晚上11:55
收件人："flutter-package/images_picker" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[flutter-package/images_picker] is it possible to show images in bottom sheet? (#36)
-----------------------------------

 

 
first of all thanks for developing this great package...
 
I felt like it is far better and more advanced package then google image_picker..
 
I am looking little customization to match my app theme and style...
 
I have two questions?
  
is it possible to show images in bottom sheet like in this or this
 
is it possible to change appbar color, ticker color and font style... etc.,
