### ISSUE TITLE
Gestures are passed through empty space on modal

### ISSUE THREAD

**Issue by Artur110** [flutter-package/images_picker#56]
## Description

**Current behavior:**
Gestures are passed through modal to the screen, where the modal was opened.

## Steps to reproduce

1.
```
 ImagesPicker.pick(
      pickType: PickType.image,
      count: 1,
      cropOpt: CropOption(),
    );
```
2. Select an image from the list.
3. Opened preview screen with 'Edit', 'Full image', and 'Done' buttons on the bottom bar.
4. Tap on the empty area on the bottom bar (see screenshot).
5. Gestures passed to screen, where ImagesPicker.pick() was called.

## Images 

![IMG_BE7B263BC2CC-1](https://user-images.githubusercontent.com/73994471/142010630-f241ff91-e023-4ed5-bc71-5e38243ebe2b.jpeg)

**Comment by chavesgu** [comment]
you can add code below to entry file`AppDelegate.swift`

> I suggest you do this, because many other flutter plugin cause this problem

```swift
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

// you need add this code
extension UIViewController {
  open override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
      // DLog("\(self) \(#function)")
  }
}
```
