### ISSUE TITLE
openCamera() never returns result if canceled

### ISSUE THREAD

**Issue by Artur110** [flutter-package/images_picker#57]
## Description

**Expected behavior:**
The method should return 'null' if no photo was taken.

**Current behavior:**
ImagePicker.openCamera() never returns value if 'close' button was pressed.

## Steps to reproduce

1. 
```
final pickedFiles = await ImagesPicker.openCamera(
      pickType: PickType.image,
    );
```
2. Tap on the closing button.
3. No value or error returned.

## Images 
![IMG_FA3C3FB7A9D7-1](https://user-images.githubusercontent.com/73994471/142011768-37232add-2e1c-4c26-99ca-13e440203cea.jpeg)

**Comment by chavesgu** [comment]
It's my fault. You can update to `1.2.6`
