### ISSUE TITLE
Record video is giving jpg return path 

### ISSUE THREAD

**Issue by ravitejaavv** [flutter-package/images_picker#59]
Not getting video path after recording the video

Android 10
Library version 1.2.7

<img width="1175" alt="Screenshot 2021-11-30 at 11 47 36 AM" src="https://user-images.githubusercontent.com/33521315/143998943-eeaa8dea-7189-4ce4-b521-4ae9cc069d93.png">

Using this code snippet to record video:
  List<Media>? res = await ImagesPicker.openCamera(
      maxTime: 60 * 60,
      pickType: PickType.video,
    );

**Comment by chavesgu** [comment]
It's my fault, I will fix it in `1.2.8`

**Comment by ravitejaavv** [comment]
> It's my fault, I will fix it in `1.2.8`

@chavesgu please fix this issue as soon as possible. I need this fix on urgent basis. 

Thanks

**Comment by chavesgu** [comment]
I have publish `1.2.8`, please wait pub update
