### ISSUE TITLE
Camera is not opening in android target sdk 31 

### ISSUE THREAD

**Issue by ravitejaavv** [flutter-package/images_picker#64]
Using images_picker 1.2.9 version

Able to open camera till target sdk 30. But camera is not opening in android target sdk 31.
We are not seeing any crash or exception in log viewer.  Tested in One Plus Nord 7

 final images = await ImagesPicker.openCamera(
      pickType: PickType.image,
    );

**Comment by chavesgu** [comment]
what's your android version. I run target sdk 31 successfully

**Comment by chavesgu** [comment]
please update `1.2.10` for `android 12 fix`

**Comment by ravitejaavv** [comment]
@chavesgu  thanks for the update. I will test and confirm

**Comment by ravitejaavv** [comment]
@chavesgu It is working fine. I am closing this issue
