### ISSUE TITLE
pickType: PickType.all is not working

### ISSUE THREAD

**Issue by Ashutoshtripathi980** [flutter-package/images_picker#68]
Code :  
  ElevatedButton( 
              child: Text('openCamera for video and image'),
              onPressed: () async {
                List<Media>? res = await ImagesPicker.openCamera(
                  pickType: PickType.all,
                  quality: 0.8,
                  maxSize: 800,
                  maxTime: 15,
                );
                print(res);
                if (res != null) {
                  print(res[0].path);
                  setState(() {
                    path = res[0].thumbPath;
                  });
                }
              },
            ),

pickType: PickType.all, is unable to pic image and video together.

**Comment by chavesgu** [comment]
open camera not support all type---- On 星期二, 18 一月 2022 20:14:54 +0800  ***@***.******@***.***> wrote ---- 
Code :    ElevatedButton( 
child: Text('openCamera for video and image'), 
onPressed: () async { 
List? res = await ImagesPicker.openCamera( 
pickType: PickType.all, 
              quality: 0.8, 
              maxSize: 800, 
              // cropOpt: CropOption( 
              //   aspectRatio: CropAspectRatio.wh16x9, 
              // ), 
              maxTime: 15, 
            ); 
            print(res); 
            if (res != null) { 
              print(res[0].path); 
              setState(() { 
                path = res[0].thumbPath; 
              }); 
            } 
          }, 
        ),

**Comment by Ashutoshtripathi980** [comment]
then , why their is an option of all type in code.

**Comment by chavesgu** [comment]
support in ios---- On 星期二, 18 一月 2022 20:37:34 +0800  ***@***.******@***.***> wrote ---- 
then , why their is an option of all type in code.
